### ISSUE TITLE
install alongside other MRtrix version

### ISSUE THREAD

**Issue by mblesac** [3Tissue/MRtrix3Tissue#14]
Dear Thijs,

Sorry for this naive question. I'm very interested to try the 3TSS algorithm, but I din't want to remove or update the MRtrix version I'm using by default (currently in some projects that are already using that version). Could I install it and don't touch the other version? my understanding is that I should be safe as long as I don't add thia version to the path, but I would like to confirm this. Thanks in advance.

Best regards,

Manuei

**Comment by thijsdhollander** [comment]
Hi Manuel,

No worries, I've gotten this question a few times recently, as people are eager to get SS3T-CSD running on their data; makes full sense.  In fact, this is one of the very reasons it's set up as a fork that basically comes "with its own dependencies" so as to say; it's the cleanest solution to guarantee the method(s) work correctly.

So basically, yes, there's no worries to install it, without affecting your current version that you depend on for ongoing projects.  Just make sure you install it in its own location (the different naming "MRtrix3Tissue" should be useful here to keep things clear.  The only thing to then be mindful of when you're actually running commands, is which installation's commands (binaries / scripts) you're calling.  You could for instance just have your existing installation in your `PATH` variable, as I suppose you've got things set up already.  If you need MRtrix3Tissue functionality, you could either call that via its absolute path on a command-per-command basis, or even create an alias for them for convenience.

If you use MRtrix3Tissue functionality in a setting/study where you also use MRtrix3 (RC3, I guess?) commands for other steps, the gist of what you need to know is currently documented here: https://3tissue.github.io/doc/install/release.html .

For SS3T-CSD, I highly recommend you use the new (2019) version of `dwi2response dhollander` that comes with MRtrix3Tissue.  This improves the 3-tissue CSD fit in ways that I've seen impact results in important ways at times; for example when dealing with very young subjects.  Finally, when using the new `dwi2response dhollander` that comes with MRtrix3Tissue, in group analyses where you want to compute average 3-tissue response functions to use across the whole population for proper quantitative comparisons, also pay attention to #12 .  Essentially, you'll also have to use the new `responsemean` command to average response functions, as the new added comment-style lines in response function files aren't backwards compatible with the older response function averaging command.

So essentially, key commands from MRtrix3Tissue are the new `dwi2response dhollander`, the new `responsemean` in case of quantitative group analyses, and the SS3T-CSD command currently named `ss3t_csd_beta1`.

Feel free to post some feedback / screenshots when you run it on your data, e.g. if you'd like to check whether results are sensible for your data!

Cheers,
Thijs

**Comment by mblesac** [comment]
Hi,

Thanks for the reply. I manage to install it keeping both versions, I will experiment with my data (neonatal) and post some results.

Best regards,

Manuel
