### ISSUE TITLE
Error with dwiresponse for portion of subjects

### ISSUE THREAD

**Issue by CallowBrainProject** [3Tissue/MRtrix3Tissue#19]
Hello, 

I am getting the following error for a decent number of the subjects I am running (1/5) and was wondering what might be causing the issue? All other steps of processing appear to work for these subjects so I am not sure why they specifically are running into this issue.

Any help decoding what the errors mean would be greatly appreciated!

dwi2response: Note that this script makes use of commands / algorithms that have relevant articles for citation. Please consult the help page (-help option) for more information.
dwi2response: 
dwi2response: Generated scratch directory: /Volumes/DANIEL/AES_mrtrix/AES136.Rest/dwi2response-tmp-UOEO2G/
dwi2response: Importing DWI data (/Volumes/DANIEL/AES_mrtrix/AES136.Rest/dwi_corrected_upsampled.mif)...

dwi2response: [ERROR] Unhandled Python exception:
dwi2response: [ERROR]   OSError: [Errno 22] Invalid argument
dwi2response: [ERROR] Traceback:
dwi2response: [ERROR]   /Applications/MRtrix3Tissue/bin/dwi2response:78 (in execute())
dwi2response: [ERROR]     run.command('mrconvert ' + path.from_user(app.ARGS.input) + ' ' + path.to_scratch('dwi.mif') + ' -strides 0,0,0,1' + grad_import_option, show=False)
dwi2response: [ERROR]   /Applications/MRtrix3Tissue/lib/mrtrix3/run.py:426 (in command())
dwi2response: [ERROR]     stderr_text = finalise_temp_file(process.iostreams[1])
dwi2response: [ERROR]   /Applications/MRtrix3Tissue/lib/mrtrix3/run.py:416 (in finalise_temp_file())
dwi2response: [ERROR]     contents = stream.read().decode('utf-8', errors='replace')

**Comment by CallowBrainProject** [comment]
I am also commonly getting the following error.

subj =  AES107 , cond =  Ex
dwi2response: 
dwi2response: Note that this script makes use of commands / algorithms that have relevant articles for citation. Please consult the help page (-help option) for more information.
dwi2response: 
dwi2response: Generated scratch directory: /Volumes/DANIEL/AES_mrtrix/AES107.Ex/dwi2response-tmp-F49UUF/
dwi2response: Importing DWI data (/Volumes/DANIEL/AES_mrtrix/AES107.Ex/dwi_corrected_upsampled.mif)...
dwi2response: Changing to scratch directory (/Volumes/DANIEL/AES_mrtrix/AES107.Ex/dwi2response-tmp-F49UUF/)
dwi2response: Computing brain mask (dwi2mask)...
dwi2response: -------
dwi2response: 2 unique b-value(s) detected: 0,1000 with 1,64 volumes
dwi2response: -------
dwi2response: Preparation:
dwi2response: * Eroding brain mask by 3 pass(es)...
dwi2response:   [ mask: 366936 -> 259058 ]
dwi2response: * Computing signal decay metric (SDM):
dwi2response:  * b=0...
dwi2response:  * b=1000...
dwi2response: * Removing erroneous voxels from mask and correcting SDM...
dwi2response:   [ mask: 259058 -> 0 ]
dwi2response: -------
dwi2response: Crude segmentation:
dwi2response: * Crude WM versus GM-CSF separation (at FA=0.2)...
dwi2response:   [ 0 -> 0 (WM) & 0 (GM-CSF) ]
dwi2response: * Crude GM versus CSF separation...
mrstats: [ERROR] Cannot output statistic of interest; no values read (empty mask?)

dwi2response: [ERROR] Error trying to calculate statistic 'median' from image 'safe_sdm.mif'

**Comment by thijsdhollander** [comment]
Hey Daniel,

That's 2 very different things you're running into here.  The first one is a bit cryptic.  At first sight, I'm guessing this is related to something strange with how you provide the path or name of the file you're inputting to `dwi2response` maybe.  What's the command you're using to run this, and on what kind of system?  Is there something different about how you run the ones that fail with that particular error?

The second case runs fine, but at the "* Removing erroneous voxels from mask and correcting SDM..." step, it removes all voxels from the mask apparently.  This means there's something strange with the intensities in that dataset, or they result in e.g. negative signal decay in all voxels.  Just as a simple check, what does a basic FA and MD map from a DTI fit look like, when run on that exact input file?  Also, does you b=0 image look normal and generally intact?

Cheers,
Thijs

**Comment by thijsdhollander** [comment]
Hi Daniel @CallowBrainProject,

Just briefly following up: did you manage to solve the issues (or obtained further insights?).

Cheers,
Thijs

**Comment by CallowBrainProject** [comment]
Hi Thijs,

Sorry for not responding. I had issues with recreating the problem. I re-ran the analysis and it seems to have worked out alright. I think occasionally the response functions or the 3tissue algorithms just happen to not "converge?" and then doesn't give an output (not sure of the exact algorithm used)? It's weird. Sometimes when running the script it fails for a subject or two and when I re-run for that subject it appears to then work?

Anyways, so far everything appears to be working for the most part. Sorry, I couldn't "diagnose" the issue and thanks for your help!

Best,
Daniel

**Comment by thijsdhollander** [comment]
Hey Daniel,

No worries at all.  Just briefly wrapping up this one for now, with a few thoughts:

> I had issues with recreating the problem. I re-ran the analysis and it seems to have worked out alright.

Yep, the issues seemed a bit unusual.  I had the feeling they might've been because of the environment you're running this on (e.g. a particular cluster system, or something relying on shared storage or similar).

> I think occasionally the response functions or the 3tissue algorithms just happen to not "converge?" and then doesn't give an output (not sure of the exact algorithm used)? It's weird. Sometimes when running the script it fails for a subject or two and when I re-run for that subject it appears to then work?

This really indicates you should check what's going on on your system, I think.  All of the relevant algorithms are entirely deterministic, and they don't really rely on iterative convergence as well.  Both response function estimation and SS3T-CSD are scripts that use temporary space to store intermediate files in, while they run.  What you're experiencing, strongly suggests that something about your temporary space isn't consistent or reliable in some ways; sometimes not correctly reading or writing an image or similar.  I would certainly diagnose your system itself, as there's many other commands in the MRtrix3 set of tools in general that are such scripts, relying on temporary space.  It's pretty risky if you can't be sure that works well of course.

> Anyways, so far everything appears to be working for the most part. Sorry, I couldn't "diagnose" the issue and thanks for your help!

Ok, so I'll close this issue for now, as it doesn't look like it's got anything to do with the software itself (e.g. a bug).  But as mentioned: keep a close eye on how any script (or command in general) performs on your system, and check the outputs carefully just to make sure!

Cheers,
Thijs
>
