### ISSUE TITLE
MRtrix3Tissue Build Error: Conflicts with Eigen 3.4

### ISSUE THREAD

**Issue by RikkiLissaman** [3Tissue/MRtrix3Tissue#32]
Hi MRtrix3Tissue maintainers!

I recently tried to download and install MRtrix3Tissue using the guidance provided here: [https://3tissue.github.io/doc/install/](url)

Unfortunately, when I got to the build stage, I encountered the following error:

> ERROR: ( 11/505) [CC] tmp/core/image_io/fetch_store.o
> 
> g++ -c -std=c++11 -DMRTRIX_BUILD_TYPE="release version" -pthread -fPIC -DMRTRIX_WORD64 -DMRTRIX_TIFF_SUPPORT -idirafter /usr/include/x86_64-linux-gnu -DMRTRIX_PNG_SUPPORT -idirafter /usr/include/libpng16 -DEIGEN_FFTW_DEFAULT -Wall -O3 -DNDEBUG -Isrc -I./core -Icmd -idirafter /usr/include/eigen3 -DEIGEN_DONT_PARALLELIZE core/image_io/fetch_store.cpp -o tmp/core/image_io/fetch_store.o
> 
> failed with output
> 
> In file included from ./core/mrtrix.h:37,
>   from ./core/raw.h:25,
>   from ./core/image_io/fetch_store.h:20,
>   from core/image_io/fetch_store.cpp:17:
> ./core/types.h:326:49: error: ‘using Vector3 = class Eigen::Matrix<double, 3, 1>’ redeclared as different kind of entity
>   326 | using Vector3 = Matrix<MR::default_type, 3, 1>;
>   | ^
> In file included from /usr/include/eigen3/Eigen/Core:295,
>   from /usr/include/eigen3/Eigen/Geometry:11,
>   from ./core/types.h:78,
>   from ./core/mrtrix.h:37,
>   from ./core/raw.h:25,
>   from ./core/image_io/fetch_store.h:20,
>   from core/image_io/fetch_store.cpp:17:
> /usr/include/eigen3/Eigen/src/Core/Matrix.h:541:1: note: previous declaration ‘template<class Type> using Vector3 = Eigen::Matrix<Type, 3, 1>’
>   541 | EIGEN_MAKE_TYPEDEFS(3, 3)
>   | ^~~~~~~~~~~~~~~~~~~
> In file included from ./core/mrtrix.h:37,
>   from ./core/raw.h:25,
>   from ./core/image_io/fetch_store.h:20,
 
Judging from the main MRtrix3 community forum, this error is related to conflicts with Eigen version 3.4, and a fix has been merged to the master branch ([https://community.mrtrix.org/t/installation-error-of-mrtrix3tissue/5233](url)). 

Is it likely that a fix will be merged for the MRtrix3Tissue fork? If not, is there a workaround? Any help would be really appreciated!

Many thanks,
Rikki

**Comment by gdevenyi** [comment]
Eigen is a header-only library, as such, all you need to do to provide a version which mrtrix3tissue supports by downloading this, https://gitlab.com/libeigen/eigen/-/archive/3.3.9/eigen-3.3.9.tar.bz2, unpacking it, and then pointing the configure script properly:
`EIGEN_CFLAGS="-isystem /path/to/the/unpacked/eign-3.3.9" ./configure`
